---
- name: Copy Oracle RPM GPG Key
  copy:
      dest: "/tmp/RPM-GPG-KEY-oracle-{{ item }}"
      src: "RPM-GPG-KEY-oracle.el{{ item }}"
  with_items:
    - 7
    - 8

- name: Import Oracle RPM GPG Key
  rpm_key:
    state: present
    key: "/tmp/RPM-GPG-KEY-oracle-{{ item }}"
  with_items:
    - 7
    - 8
    
- name: "Install oracle_{{ java_type }} {{ java_version }}"
  yum:
    name: "https://s3.amazonaws.com/xxxxxxx/xxxxxx_{{ java_type }}/{{ java_type }}-{{ java_version }}-linux-x64.rpm"
    state: present

- set_fact:
    done_{{role_path|basename}}: true